name: Maven and Docker Build

on:
  workflow_dispatch:
    inputs:      
      deployment:
        description: 'Deployment[dev,test,uat,prod]'
        required: true
        default: 'dev'

jobs:
  build:
    #Setup Environment
    runs-on: ubuntu-latest
    env:
      MY_ENV: "dev"
      
    steps:  
      - name: "Change Values Bases on Environment Variables Dev"
        if: ${{ github.event.inputs.deployment == 'dev' }}        
        run: |
         echo "Deploying to  ${{github.event.inputs.deployment}}"
         echo '::set-output name=NAMESPACE::tlf-dev'
    
      - name: "Change Values Bases on Environment Variables Test"
        if: ${{ github.event.inputs.deployment == 'test' }}        
        run: echo "::set-env name=MY_ENV::test"
         
      - name: Check Value
        run: echo  ${{ env.MY_ENV }} 
 
