name: Maven and Docker Build

on:
  workflow_dispatch:
    inputs:      
      deployment:
        description: 'Deployment[dev,test,uat,prod]'
        required: true
        default: 'dev'

jobs:
  build:
    #Setup Environment
    runs-on: ubuntu-latest
   
    steps:  
      - name: "Change Values Bases on Environment Variables Dev"
        if: ${{ github.event.inputs.deployment == 'dev' }}        
        run: |
         echo "Deploying to  ${{github.event.inputs.deployment}}"
         echo '::set-output name=NAMESPACE::tlf-dev'
    
      - name: Get Namespace
        run: echo "The selected color is ${{ steps.outputs.NAMESPACE }}"    
    
